const USER_TYPES = {
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER_LIST_PENDING: "GET_USER_LIST_PENDING",
  GET_USER_LIST_FULFILLED: "GET_USER_LIST_FULFILLED",
  GET_USER_LIST_REJECTED: "GET_USER_LIST_REJECTED",
  GET_USER: "GET_USER",
  GET_USER_PENDING: "GET_USER_PENDING",
  GET_USER_FULFILLED: "GET_USER_FULFILLED",
  GET_USER_REJECTED: "GET_USER_REJECTED",
  DELETE_USER: "DELETE_USER",
  DELETE_USER_PENDING: "DELETE_USER_PENDING",
  DELETE_USER_FULFILLED: "DELETE_USER_FULFILLED",
  DELETE_USER_REJECTED: "DELETE_USER_REJECTED",
  CHANGE_USER: "CHANGE_USER",
  CHANGE_USER_PENDING: "CHANGE_USER_PENDING",
  CHANGE_USER_FULFILLED: "CHANGE_USER_FULFILLED",
  CHANGE_USER_REJECTED: "CHANGE_USER_REJECTED",
  CLEAR_MESSAGES: "CLEAR_MESSAGES",
};

export default USER_TYPES;
