const AUTH_TYPES = {
  LOGIN: "LOGIN",
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_FULFILLED: "LOGIN_FULFILLED",
  LOGIN_REJECTED: "LOGIN_REJECTED",
  LOGOUT: "LOGOUT",
  SET_TOKEN: "SET_TOKEN",
};

export default AUTH_TYPES;
